language: go

go:
  - 1.4
  - tip

before_script:
  - go get -u github.com/golang/lint/golint

script:
  - go test -race
  - go tool vet -v USBEnttecProAdaptor.go  driver.go
  - golint .

matrix:
  fast_finish: true
  allow_failures:
    - go: tip